version: "3.7"

services:
    nuxt:
        image: node:12.14.1
        restart: always
        working_dir: /src
        volumes:
            - ./app:/src
        tty: true
        environment:
            HOST: "0.0.0.0"
        ports:
            - "3000:3000"
    nginx:
        image: nginx:1.17.8
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./nginx:/etc/nginx/conf.d
        depends_on:
            - nuxt
